# Site settings
title:          Kyoo Ee
description:    "Good good study, day day up."
url:            https://github.com/kyooee516/kyooee516.github.io

# Author
author:
  name:         Kyoo Ee
  email:        kyooee516@gmail.com
  url:          https://github.com/kyooee516/kyooee516.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        2
  min_common_tags:  2

# Links to social media
social:
  email: kyooee516@gmail.com@gmail.com
  github: https://github.com/kyooee516
#  twitter: https://twitter.com
#  linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
